FROM dev_basic:stable
MAINTAINER jinal--shah <jnshah@gmail.com>
LABEL Name="dev_librarian_packer_aws" Vendor="sortuniq" Version="0.0.1" \
      Description="run Makefiles and librarian-puppet to packerise for aws"
# build instructions:
# img_name=$(grep '^LABEL ' ./Dockerfile | sed -e 's/.*Name="\([^"]\+\).*/\1/')
# tag_version=$(grep '^LABEL ' ./Dockerfile | sed -e 's/.*Version="\([^"]\+\).*/\1/')
# docker build -f ./Dockerfile.dev --no-cache=true --rm --tag $img_name:$tag_version .
# docker rmi $img_name:stable 2>/dev/null
# docker tag $img_name:$tag_version $img_name:stable

ARG PACKER_VERSION

ENV APP="packer"                         \
    VERSION=$PACKER_VERSION              \
    SCRIPTS_LOCAL="build-scripts-alpine" \
    SCRIPTS_DOCKER="/var/tmp/scripts"

COPY $SCRIPTS_LOCAL $SCRIPTS_DOCKER

RUN chmod a+x $SCRIPTS_DOCKER/*                        \
    && $SCRIPTS_DOCKER/install_librarian_and_puppet.sh \
    && $SCRIPTS_DOCKER/install_packer.sh               \
    && $SCRIPTS_DOCKER/install_awscli.sh               \
    && apk --no-cache --update sed make jq             \
    && rm -rf /var/cache/apk/* $SCRIPTS_DOCKER
  
CMD ["/bin/true"]
